# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-15 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarkedPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.DecimalField(decimal_places=7, max_digits=15)),
                ('Longitude', models.DecimalField(decimal_places=7, max_digits=15)),
                ('Notes', models.CharField(max_length=2000)),
            ],
        ),
    ]
